apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authelia-external
  namespace: authelia
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.middlewares: authelia-secure-headers@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - auth.jlmitra.com
    secretName: authelia-external-tls
  rules:
  - host: auth.jlmitra.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: authelia-svc
            port:
              number: 80
