apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configuration.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - ingress-external.yaml
  - middleware.yaml
  - middleware-headers.yaml
