apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: silverbullet-external
  namespace: silverbullet
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.middlewares: authelia-secure-headers@kubernetescrd,authelia-authelia-forwardauth@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - sb.jlmitra.com
    secretName: silverbullet-external-tls
  rules:
  - host: sb.jlmitra.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: silverbullet
            port:
              number: 80
