apiVersion: v1
kind: Service
metadata:
  name: silverbullet
  namespace: silverbullet
spec:
  selector:
    app: silverbullet
  ports:
  - name: http
    port: 80
    targetPort: 3000
  type: NodePort
